site_name: bnbong's tech blog
site_description: 이준혁의 기술 관련 블로그
site_url: https://bnbong.github.io
repo_name: bnbong/bnbong.github.io
repo_url: https://github.com/bnbong/bnbong.github.io
theme:
  custom_dir: overrides
  name: material
  font:
    text: JetBrains Mono
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: brown
      toggle:
        icon: material/brightness-7  # current mode : light
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: brown
      toggle:
        icon: material/brightness-4  # current mode : dark
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
    - toc.follow
  language: ko
plugins:
  - blog:
      blog_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      draft: true
      draft_on_serve: false
      draft_if_future_date: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      comments_path: "#__comments"
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans KR
  - tags:
      tags_file: blog/tags.md

not_in_nav: |
  /drafts/**/*.md

nav:
- About Me: index.md
- Blog:
  - blog/index.md
  - blog/tags.md
- Projects:
  - projects/index.md
  - 개인 프로젝트 :
    - Bifrost : projects/bifrost.md
    - TooKindFriendChat : projects/tookindfriendchat.md
    - JaramUniv_Sugang-API : projects/univapi.md
    - rickTcal_DayLife : projects/ricktcal.md
    - KakaoTalk-channel-WeatherToday : projects/kakaotalk-weatherforecast.md
  - 팀 프로젝트 :
    - Project-Pinned : projects/project-pinned.md
    - Awesome Chatting App : projects/awesomechat.md
    - Mugip : projects/mugip.md
    - KBuddy : projects/kbuddy.md
    - Jaram Groupware Hub : projects/jgw-hub.md
    - Jaram Groupware Penalty Python : projects/jgw-penalty-python.md
    - Jaram Groupware Attendance Python : projects/jgw-attendance-python.md
    - Phishing QR detector : projects/qr-phishing-detector.md
  - 오픈소스 프로젝트:
    - Azure SDK for Python : projects/azure-sdk-python.md
    - Azure SDK for Python Korean Docs : projects/azure-sdk-python-kor.md
    - FastAPI FastKit : projects/fastapi-fastkit.md
    - Blog Post Workflow : projects/blog-post-workflow.md
    - FEMU Monitoring : projects/femu-monitoring.md
extra:
  status:
    new: Recently added
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bnbong
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%EC%A4%80%ED%98%81-%EC%9D%B4-669733231/
    - icon: fontawesome/solid/globe
      link: https://blog.naver.com/bnbong
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/j_hyeok__lee/
    - icon: fontawesome/solid/envelope
      link: mailto:bbbong9@gmail.com
    - icon: material/rss
      link: /feed_rss_updated.xml
      name: Subscribe to our RSS Feed
  tags:
    <tag>: <identifier>
  blog:
    dir: blog
    author: bnbong
    author_image: https://avatars.githubusercontent.com/bnbong
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true
    archive_toc: true
    pagination_per_page: 10
    pagination_keep_content: true
  analytics:
    provider: google
    id: G-G1E1JBX2WR

markdown_extensions:
  - toc:
      title: 이 페이지의 요소들
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - hooks/socialmedia.py

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2019-2025 bnbong
